
name: Trigger Jenkins Job from GitHub

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Trigger Jenkins via REST API
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/build?token=$JENKINS_TRIGGER_TOKEN" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN"
        env:
          JENKINS_URL: 'http://13.48.106.243:8080/'
          JENKINS_USER: 'Sattwik'
          JENKINS_API_TOKEN: '11ecac409b017881fe860cbc6523278adc'
          JENKINS_JOB_NAME: 'FreeStyleProject'
          JENKINS_TRIGGER_TOKEN: 'trigger-from-github'
